name: Run Staging Tests

on:
  push:
    branches:
      - main

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install AnyConnect VPN & Login
        run: |
          sudo apt-get update
          sudo /sbin/modprobe tun
          sudo apt-get install -y openconnect
          echo "${{ secrets.NETLAB_PASSWORD }}" | sudo openconnect --user=${{ secrets.NETLAB_USERNAME }} --passwd-on-stdin vpnnetlab.fhict.nl -b

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 192.168.144.5 >> ~/.ssh/known_hosts

      - name: Transfer Project Files
        run: |
          ssh -o StrictHostKeyChecking=no student@192.168.144.5 "mkdir -p /home/student/sentimate"
          scp -o StrictHostKeyChecking=no -r ./mood-tracking-app/tests/* student@192.168.144.5:/home/student/sentimate

      - name: Install K6
        run: |
          ssh -o StrictHostKeyChecking=no student@192.168.144.5 << EOF
            sudo apt-get update
            sudo apt-get install -y gnupg2
            curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
            echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
            sudo apt-get update
            sudo apt-get install -y k6
          EOF

      - name: Authenticate K6 with Grafana Cloud
        run: |
          ssh -o StrictHostKeyChecking=no student@192.168.144.5 "k6 login cloud --token ${{ secrets.GRAFANA_CLOUD_TOKEN }}"

      - name: Run K6 Test in the Cloud
        run: |
          ssh -o StrictHostKeyChecking=no student@192.168.144.5 << EOF
            cd /home/student/sentimate
            k6 cloud script.js
          EOF
